### PR TITLE
Webkit/Chrome requires xhr to be open before setting headers

### PR DESCRIPTION
**Pull request by erithmetic**
At least this seemed be the case in my browser

### CODE REVIEW

**Comment by jxson** [comment]
I am having the same issue in Safari Webkit (Version 5.1.1 (7534.51.22) )

**Comment by erithmetic** [comment]
Also note from MDN: https://developer.mozilla.org/en/XMLHttpRequest#setRequestHeader()

```
Sets a HTTP request header for HTTP requests. You must call open before setting the request headers.
```

**Comment by zahanm** [comment]
+1 on getting this merged in @substack , it's absolutely necessary for CORS stuff in modern browsers.

**Comment by zahanm** [comment]
:) thanks.

**Comment by jxson** [comment]
yes, thank you!

**Pull request merged**
