### PR TITLE
add HTTP.STATUS_CODES

### PR DESCRIPTION
**Pull request by nlacasse**
HTTP.STATUS_CODES.

They come in handy some times.

This is copied directly from node's http.js.

### CODE REVIEW

**Comment by nlacasse** [comment]
@substack Is there a reason you don't want this patch?  `exports.STATUS_CODES` is part of node's http module.  It should be in this module too.

**Comment by ryanfitz** [comment]
I'm currently running to a bug because of no status_codes on the http module. Any updates on this pull?

**Comment by nlacasse** [comment]
@substack @ryanfitz I realized a while ago that I botched this pull request.  The STATUS_CODES should be on `http`, not `Request`.

I have a fork of http-browserify with the STATUS_CODES in the right place, and also some other changes:
https://github.com/spire-io/http-browserify/blob/master/browser.js

**Comment by jfirebaugh** [comment]
`http.STATUS_CODES` was added in 4934703e37cee7c75bd39b9fe892d7296305a976; this can be closed.

**Pull request closed without merging**
