### PR TITLE
full support for node url object

### PR DESCRIPTION
**Pull request by panthershark**
Fixed this issue - https://github.com/substack/http-browserify/issues/27

Attached uri to the Request instance so that I could write a few unit tests.  Added unit tests for simple case and for full node url object.

Please let me know if there is anything further I can do.

### CODE REVIEW

**Comment by ameensol** [comment]
@substack Would be awesome if you could implement this pull request. The node-alchemy module is currently incompatible with browserify due to the lack of support for node url object. See framingeinstein/node-alchemy#4.

**Comment by panthershark** [comment]
@ameensol - Here is my current workaround until this PR is merged.

in package.json put this entry.
"http-browserify": "git+https://github.com/tommydudebreaux/http-browserify.git"

then in the browserify settings, create an alias that points from "http" to "./node_modules/http-browserify/index.js"

**Comment by ghost** [comment]
Please don't check in gitignore files ever. They cause conflicts if a gitignore already exists.

**Comment by ameensol** [comment]
@tommydudebreaux I already built my own workaround by forking the node-alchemy module and using browser-request instead of http, but thanks anyways!

**Comment by panthershark** [comment]
bump

**Comment by ghost** [comment]
Merged in 0.3.0. Make sure to bug https://github.com/alexgorbatchev/node-browser-builtins to get this into browserify core.

**Comment by ghost** [comment]
ping @aredriel we should make sure this patch didn't regress over the [pull/30](https://github.com/substack/http-browserify/pull/30) patch that went in. I had to merge this by hand since it touched a lot of the same lines and there was some movement of the scheme handling too.

**Comment by panthershark** [comment]
@substack  - Thanks for the merge.

**Pull request closed without merging**
