### PR TITLE
Behave more like Node http

### PR DESCRIPTION
**Pull request by bmpvieira**
Emit Buffers instead of ArrayBuffers and if encoding is null return Buffer.
These also allow to have [request](http://github.com/mikeal/request) behave the same way on the browser and server.

### CODE REVIEW

**Comment by ghost** [comment]
Can you submit a less noisy version of this?

**Comment by bmpvieira** [comment]
Sure, sorry about that. My editor had "trim white spaces" on.

**Comment by joewood** [comment]
Will this pull request be merged?  This is causing issues with some npm packages not working in browserify.

**Comment by cameronr** [comment]
+1 on merging this PR

**Pull request closed without merging**
